title: "Covid simulation"
description: "Documentation for the covid simulation developed by the IDAS team."
#baseurl: "https://josephpb.github.io"
#url: "/covidmodelling"
remote_theme: pmarsceill/just-the-docs
markdown: kramdown
color_scheme: "light"
plugins:
  - jekyll-remote-theme
mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'
